//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuuxPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuuxPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap alfred_e_neuman {
            get {
                object obj = ResourceManager.GetObject("alfred_e_neuman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap button_outline_right {
            get {
                object obj = ResourceManager.GetObject("button_outline_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_off {
            get {
                object obj = ResourceManager.GetObject("checkbox_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_off_disabled {
            get {
                object obj = ResourceManager.GetObject("checkbox_off_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_on {
            get {
                object obj = ResourceManager.GetObject("checkbox_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkbox_on_disabled {
            get {
                object obj = ResourceManager.GetObject("checkbox_on_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_advance_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_advance_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_back_disabled {
            get {
                object obj = ResourceManager.GetObject("cpl_back_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_back_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_back_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_background {
            get {
                object obj = ResourceManager.GetObject("cpl_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_center {
            get {
                object obj = ResourceManager.GetObject("cpl_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_fwd_disabled {
            get {
                object obj = ResourceManager.GetObject("cpl_fwd_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_fwd_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_fwd_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_mute {
            get {
                object obj = ResourceManager.GetObject("cpl_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_mute_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_mute_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_nomute_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_nomute_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_now_playing_disabled {
            get {
                object obj = ResourceManager.GetObject("cpl_now_playing_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_now_playing_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_now_playing_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_now_playing_on {
            get {
                object obj = ResourceManager.GetObject("cpl_now_playing_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_now_playing_on_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_now_playing_on_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_pause {
            get {
                object obj = ResourceManager.GetObject("cpl_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_pause_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_pause_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_play_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_play_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_repeat_disabled {
            get {
                object obj = ResourceManager.GetObject("cpl_repeat_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_repeat_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_repeat_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_repeat_on {
            get {
                object obj = ResourceManager.GetObject("cpl_repeat_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_repeat_on_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_repeat_on_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_shuffle_disabled {
            get {
                object obj = ResourceManager.GetObject("cpl_shuffle_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_shuffle_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_shuffle_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_stop_disabled {
            get {
                object obj = ResourceManager.GetObject("cpl_stop_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_stop_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_stop_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_volume_ball {
            get {
                object obj = ResourceManager.GetObject("cpl_volume_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_volume_ball_highlighted {
            get {
                object obj = ResourceManager.GetObject("cpl_volume_ball_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cpl_volume_slider {
            get {
                object obj = ResourceManager.GetObject("cpl_volume_slider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_bar_background {
            get {
                object obj = ResourceManager.GetObject("filter_bar_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_bar_x {
            get {
                object obj = ResourceManager.GetObject("filter_bar_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_bar_x_highlighted {
            get {
                object obj = ResourceManager.GetObject("filter_bar_x_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_button_background {
            get {
                object obj = ResourceManager.GetObject("filter_button_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_index_close {
            get {
                object obj = ResourceManager.GetObject("filter_index_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_index_close_hover {
            get {
                object obj = ResourceManager.GetObject("filter_index_close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_outline_background {
            get {
                object obj = ResourceManager.GetObject("filter_outline_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_outline_left {
            get {
                object obj = ResourceManager.GetObject("filter_outline_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_outline_right {
            get {
                object obj = ResourceManager.GetObject("filter_outline_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gamepad {
            get {
                object obj = ResourceManager.GetObject("gamepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_screen_graphic {
            get {
                object obj = ResourceManager.GetObject("help_screen_graphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player {
            get {
                object obj = ResourceManager.GetObject("mini_player", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_advance_hover {
            get {
                object obj = ResourceManager.GetObject("mini_player_advance_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_back_disabled {
            get {
                object obj = ResourceManager.GetObject("mini_player_back_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_back_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_back_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_exit {
            get {
                object obj = ResourceManager.GetObject("mini_player_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_exit_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_exit_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_fwd_disabled {
            get {
                object obj = ResourceManager.GetObject("mini_player_fwd_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_fwd_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_fwd_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_mute_off_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_mute_off_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_mute_on {
            get {
                object obj = ResourceManager.GetObject("mini_player_mute_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_mute_on_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_mute_on_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_pause {
            get {
                object obj = ResourceManager.GetObject("mini_player_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_pause_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_pause_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_play_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_play_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_volume_down_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_volume_down_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mini_player_volume_up_highlighted {
            get {
                object obj = ResourceManager.GetObject("mini_player_volume_up_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon quuxfile {
            get {
                object obj = ResourceManager.GetObject("quuxfile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon quuxplayer {
            get {
                object obj = ResourceManager.GetObject("quuxplayer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radio_highlighted {
            get {
                object obj = ResourceManager.GetObject("radio_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radio_on {
            get {
                object obj = ResourceManager.GetObject("radio_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radio_on_highlighted {
            get {
                object obj = ResourceManager.GetObject("radio_on_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rss {
            get {
                object obj = ResourceManager.GetObject("rss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_down {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_down_highlighted {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_down_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_skip_a {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_skip_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_skip_a_highlighted {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_skip_a_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_skip_z {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_skip_z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_skip_z_highlighted {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_skip_z_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_up {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_bar_up_highlighted {
            get {
                object obj = ResourceManager.GetObject("scroll_bar_up_highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stars {
            get {
                object obj = ResourceManager.GetObject("stars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TaskDialogArrow {
            get {
                object obj = ResourceManager.GetObject("TaskDialogArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap track_details_background {
            get {
                object obj = ResourceManager.GetObject("track_details_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
